# Exercise: Job Failures
version: 2.1

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          return 1
      - run:
          name: "Say hello"
          command: "echo Job Faild "
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - my_job